#!/bin/sh
module="aesdchar"
device="aesdchar"
mode="664"

module_load () {
		module=$1
		# Use the same name for the device as the name used for the module
		device=$1
		# Support read/write for owner and group, read only for everyone using 644
		mode="664"

        cd `dirname $0`
        set -e
        # Group: since distributions do it differently, look for wheel or use staff
        if grep -q '^staff:' /etc/group; then
            group="staff"
        else
            group="wheel"
        fi

        if [ -e ${module}.ko ]; then
            echo "Loading local built file ${module}.ko"
            insmod ./$module.ko $* || exit 1
        else
            echo "Local file ${module}.ko not found, attempting to modprobe"
            modprobe ${module} || exit 1
        fi
        major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
        rm -f /dev/${device}
        mknod /dev/${device} c $major 0
        chgrp $group /dev/${device}
        chmod $mode  /dev/${device}
	}

	module_unload () {
		module=$1
		device=$1

		cd `dirname $0`
        # invoke rmmod with all arguments we got
        rmmod $module || exit 1

        # Remove stale nodes

        rm -f /dev/${device}
	}

# Group: since distributions do it differently, look for wheel or use staff
if grep -q '^staff:' /etc/group; then
    group="staff"
else
    group="wheel"
fi

if [ "$1" = "start" ]; then
    echo "Loading aesdchar"
    ignore=$(module_load aesdchar)

elif [ "$1" = "stop" ]; then
    echo "Unloading aesdchar"
    ignore=$(module_unload aesdchar)

else
    echo "Usage: $0 {start|stop}"
    exit 1
fi

exit 0