#!/bin/sh

case "$1" in
    start)
        echo "Starting whiteboard_wiper ..."
        /usr/bin/whiteboard_wiper/whiteboard_wiper &
        ;;
    stop)
        killall whiteboard_wiper 2>/dev/null
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
exit 0